title: Jinrui Zhang's Homepage
page-top-title: Jinrui Zhang
top-section-bg-text: Computational Mathematics
home-subtitle: Jinrui Zhang&ensp;|&ensp;张金锐
copyright-text: '&copy; Jinrui Zhang 2023-2025. All Rights Reserved.'
